ALTER TABLE answer_drafts ADD COLUMN IF NOT EXISTS sent_by VARCHAR(120);
ALTER TABLE answer_drafts ADD COLUMN IF NOT EXISTS sent_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE answer_drafts ADD COLUMN IF NOT EXISTS send_channel VARCHAR(32);
ALTER TABLE answer_drafts ADD COLUMN IF NOT EXISTS send_message_id VARCHAR(255);
