ALTER TABLE answer_drafts ADD COLUMN IF NOT EXISTS reviewed_by VARCHAR(120);
ALTER TABLE answer_drafts ADD COLUMN IF NOT EXISTS review_comment VARCHAR(2000);
ALTER TABLE answer_drafts ADD COLUMN IF NOT EXISTS reviewed_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE answer_drafts ADD COLUMN IF NOT EXISTS approved_by VARCHAR(120);
ALTER TABLE answer_drafts ADD COLUMN IF NOT EXISTS approve_comment VARCHAR(2000);
ALTER TABLE answer_drafts ADD COLUMN IF NOT EXISTS approved_at TIMESTAMP WITH TIME ZONE;
